### ISSUE TITLE
libqalculate-5.10.0 FTBFS with GCC 16

### ISSUE THREAD

**Issue by renodr** [Qalculate/libqalculate#979]
While working on implementing GCC 16.1 over at Linux From Scratch, we've been rebuilding every package against GCC 16.

Relevant package versions include GCC 16.1, libxml2-2.15.3, curl-8.20.0, and ICU-78.3.

libqalculate-5.10.0 when downloaded from the GitHub Releases section fails to build with GCC 16. I confirmed this on Arch Linux as well after reading #916 and get the following error on both platforms:

```
libtool: compile:  g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I.. -I.. -DPACKAGE_DATA_DIR=\"/usr/share\" -I/usr/include/libxml2 -g -O2 -MT Calculator.lo -MD -MP -MF .deps/Calculator.Tpo -c Calculator.cc  -fPIC -DPIC -o .libs/Calculator.o
In file included from /usr/include/unicode/ucasemap.h:29,
                 from Calculator.cc:39:
/usr/include/unicode/localpointer.h:559:26: error: parameter declared 'auto'
  559 | template <typename Type, auto closeFunction>
      |                          ^~~~
/usr/include/unicode/localpointer.h:571:76: error: template argument 2 is invalid [-Wtemplate-body]
  571 |     explicit LocalOpenPointer(std::unique_ptr<Type, decltype(closeFunction)> &&p)
      |                                                                            ^
/usr/include/unicode/localpointer.h:581:78: error: template argument 2 is invalid [-Wtemplate-body]
  581 |     LocalOpenPointer &operator=(std::unique_ptr<Type, decltype(closeFunction)> &&p) {
      |                                                                              ^
/usr/include/unicode/localpointer.h:597:59: error: template argument 2 is invalid [-Wtemplate-body]
  597 |     operator std::unique_ptr<Type, decltype(closeFunction)> () && {
      |                                                           ^
/usr/include/unicode/ucasemap.h:99:1: note: invalid template non-type parameter
   99 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUCaseMapPointer, UCaseMap, ucasemap_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:681: Calculator.lo] Error 1
make[2]: Leaving directory '/home/renodr/libqalculate-5.10.0/libqalculate'
make[1]: *** [Makefile:531: all-recursive] Error 1
make[1]: Leaving directory '/home/renodr/libqalculate-5.10.0'
```

These errors are valid when using std=c++11, as 'auto' isn't supported for templates there.

I tried against git master though, as well as in the tarball by running ```autoreconf -fiv```, and regenerating the build files seems to resolve this problem and doesn't lock it to C++11 anymore.

**On GCC 15 without autoreconf**

```
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking dependency style of g++... gcc3

```

**On GCC 16 without autoreconf**

```
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... -std=gnu++11
checking dependency style of g++ -std=gnu++11... gcc3
```

**On GCC 16 with autoreconf**

```
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C preprocessor... gcc -E
```

I think the problem is caused by the version of autoconf that was used when creating libqalculate-5.10.0, as autoconf-2.73 (released on 3/20/2026) includes the following change for GCC 16 compatibility:

```
*** AC_PROG_CXX no longer attempts to switch to C++98 or C++11.
  Instead, it uses the compiler's default, which you can override
  by configuring with something like CXX='g++ -std=gnu++11'.
  This reverts to Autoconf 2.69 behavior, and also fixes a bug where
  AC_PROG_CXX rejected C++20 compilers.
```
