### PR TITLE
Require autoconf >= 2.73 to avoid GCC 16 FTBFS (fixes #979)

### LINKED ISSUE #979: libqalculate-5.10.0 FTBFS with GCC 16
While working on implementing GCC 16.1 over at Linux From Scratch, we've been rebuilding every package against GCC 16.

Relevant package versions include GCC 16.1, libxml2-2.15.3, curl-8.20.0, and ICU-78.3.

libqalculate-5.10.0 when downloaded from the GitHub Releases section fails to build with GCC 16. I confirmed this on Arch Linux as well after reading #916 and get the following error on both platforms:

```
libtool: compile:  g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I.. -I.. -DPACKAGE_DATA_DIR=\"/usr/share\" -I/usr/include/libxml2 -g -O2 -MT Calculator.lo -MD -MP -MF .deps/Calculator.Tpo -c Calculator.cc  -fPIC -DPIC -o .libs/Calculator.o
In file included from /usr/include/unicode/ucasemap.h:29,
                 from Calculator.cc:39:
/usr/include/unicode/localpointer.h:559:26: error: parameter declared 'auto'
  559 | template <typename Type, auto closeFunction>
      |                          ^~~~
/usr/include/unicode/localpointer.h:571:76: error: template argument 2 is invalid [-Wtemplate-body]
  571 |     explicit LocalOpenPointer(std::unique_ptr<Type, decltype(closeFunction)> &&p)
      |                                                                            ^
/usr/include/unicode/localpointer.h:581:78: error: template argument 2 is invalid [-Wtemplate-body]
  581 |     LocalOpenPointer &operator=(std::unique_ptr<Type, decltype(closeFunction)> &&p) {
      |                                                                              ^
/usr/include/unicode/localpointer.h:597:59: error: template argument 2 is invalid [-Wtemplate-body]
  597 |     operator std::unique_ptr<Type, decltype(closeFunction)> () && {
      |                                                           ^
/usr/include/unicode/ucasemap.h:99:1: note: invalid template non-type parameter
   99 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUCaseMapPointer, UCaseMap, ucasemap_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:681: Calculator.lo] Error 1
make[2]: Leaving directory '/home/renodr/libqalculate-5.10.0/libqalculate'
make[1]: *** [Makefile:531: all-recursive] Error 1
make[1]: Leaving directory '/home/renodr/libqalculate-5.10.0'
```

These errors are valid when using std=c++11, as 'auto' isn't supported for templates there.

I tried against git master though, as well as in the tarball by running ```autoreconf -fiv```, and regenerating the build files seems to resolve this problem and doesn't lock it to C++11 anymore.

**On GCC 15 without autoreconf**

```
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking dependency style of g++... gcc3

```

**On GCC 16 without autoreconf**

```
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... -std=gnu++11
checking dependency style of g++ -std=gnu++11... gcc3
```

**On GCC 16 with autoreconf**

```
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C preprocessor... gcc -E
```

I think the problem is caused by the version of autoconf that was used when creating libqalculate-5.10.0, as autoconf-2.73 (released on 3/20/2026) includes the following change for GCC 16 compatibility:

```
*** AC_PROG_CXX no longer attempts to switch to C++98 or C++11.
  Instead, it uses the compiler's default, which you can override
  by configuring with something like CXX='g++ -std=gnu++11'.
  This reverts to Autoconf 2.69 behavior, and also fixes a bug where
  AC_PROG_CXX rejected C++20 compilers.
```

### PR DESCRIPTION
**Pull request by jadhavgaurav**
## Problem

Building against GCC 16 fails as reported in #979:

```
error: parameter declared 'auto'
template <typename Type, auto closeFunction>
```

This comes from `<unicode/localpointer.h>` (ICU), which uses an `auto`
non-type template parameter — a C++17 feature. It only shows up when the
compiler is forced into `-std=gnu++11` mode, which is what a `configure`
script generated by autoconf < 2.73 does via `AC_PROG_CXX`. `configure.ac`
itself never hardcodes a C++ standard; the forced flag comes entirely from
whichever autoconf version last regenerated `configure`.

Autoconf 2.73 changed `AC_PROG_CXX` to stop forcing C++98/C++11 and defer
to the compiler's own default instead, which is why the issue reporter
found that running `autoreconf -fiv` against a recent autoconf made the
problem disappear.

## Fix

Add `AC_PREREQ([2.73])` to `configure.ac`. This doesn't change behavior
for anyone already regenerating the build system with a modern autoconf
(2.73+), but it makes `autoreconf`/`autoconf` fail loudly with an old
autoconf instead of silently baking a `-std=gnu++11` FTBFS into the next
release tarball.

## Testing

I don't have a way to install an autoconf older than 2.73 to reproduce the
*regeneration* step exactly as it would have happened for the 5.10.0
release, but I did reproduce and confirm the underlying compiler-level bug
directly with real GCC 16.2.0 and ICU 78.3 (Homebrew on macOS):

- `g++-16 -std=gnu++11 -I<icu>/include -c` on a TU including
  `<unicode/ucasemap.h>` reproduces the exact error from the issue.
- The same compile with no forced `-std=` (compiler default, C++20 on this
  GCC 16 build) succeeds.
- Regenerated the whole build system with `autoreconf -fiv` (autoconf
  2.73, automake 1.18.1) with this patch applied — the resulting
  `configure` contains no forced `-std=gnu++11`/`-std=c++11` anywhere.
- Ran `./configure` + full `make` with `CXX=g++-16 CC=gcc-16` against
  real libxml2 2.15.3, ICU 78.3, gmp 6.3.0, mpfr 4.2.2 — clean build.
- Ran the built `src/test` and `src/unittest` binaries directly (all
  batches — geometry, strings, explog, bitwise, units, solver,
  percentages, polynomial, calculus, limits, variables, operators, dates,
  matrixvector, stats, parser, numberbase — pass).
- `make check` itself fails in this environment, but only because of an
  unrelated shell-quoting issue in Automake's parallel test driver caused
  by my local working directory containing spaces — not a regression from
  this change (confirmed by running the same test binaries directly).

## Disclosure

This PR was prepared with AI assistance (Claude). The root-cause analysis,
patch, and all verification described above were reviewed and confirmed
by me before submitting.

### CODE REVIEW

**Comment by hanna-kn** [comment]
This has been fixed in the tarballs for libqalculate version >= 5.11. I see no reason to cause failure if anyone wants to run autoconf on a system with autoconf < 2.73 (especially considering that version 2.73 was recently released).

**Comment by jadhavgaurav** [comment]
Understood, and fair enough. If the tarballs are already fixed from 5.11 on, gating the source-checkout build behind autoconf >= 2.73 isn't worth the friction you're describing for anyone still on an older autoconf.

Happy to close this, or if it's useful I can instead add a comment-only note in configure.ac pointing at this thread for anyone who hits the GCC 16 error building from a pre-5.11 checkout, without changing the actual requirement. Let me know which you'd prefer, or feel free to close it yourself either way.
